language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-9.2.11.1

gemfile:
  - gemfiles/Gemfile.activerecord-6.0
  - gemfiles/Gemfile.activerecord-5.2
  - gemfiles/Gemfile.activerecord-5.1
  - gemfiles/Gemfile.activerecord-5.0
  - gemfiles/Gemfile.activerecord-4.2

matrix:
  allow_failures:
    - rvm: jruby-9.2.11.1
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.activerecord-6.0
    - rvm: 2.3
      gemfile: gemfiles/Gemfile.activerecord-6.0
    - rvm: 2.4
      gemfile: gemfiles/Gemfile.activerecord-6.0
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.activerecord-5.2
    - rvm: jruby-9.2.11.1
      gemfile: gemfiles/Gemfile.activerecord-6.0
      gemfile: gemfiles/Gemfile.activerecord-5.1
      gemfile: gemfiles/Gemfile.activerecord-5.0
      gemfile: gemfiles/Gemfile.activerecord-4.2

before_script:
  - mysql -e 'create database sequel_activerecord_connection;'
  - psql -c 'create database sequel_activerecord_connection;' -U postgres

cache: bundler

script: "bundle exec rake test"

addons:
  postgresql: "9.6"

services:
  - postgresql
  - mysql
